javac SnippetConvertingClient.java SnippetElementsExtractingClient.java HTMLSnippetElementFlyweightFactory.java HTMLSnippetElementFlyweight.java HTMLSnippetElementConcreteFlyweight.java
java SnippetConvertingClient
